spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/scaffold
    username: local
    password: local_pwd
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

aws:
  accessKey: AKIAQT7OSLRQNTHVIGY4
  secretKey: 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
  region: us-east-2
