version: 1
update_configs:
  - package_manager: "java:gradle"
    directory: "/"
    update_schedule: "daily"
    default_labels:
      - "dependencies"
      - "dependabot"
    allowed_updates:
      - match:
          update_type: "all"
